import * as reservation from "@/features/reservations/types/reservation";

export const mockReservations: reservation.MyReservationItem[] = [
  {
    id: 1,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 101,
      title: "함께 배우면 즐거운 스트릿 댄스",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1001,
    status: "pending",
    reviewSubmitted: false,
    totalPrice: 10000,
    headCount: 1,
    date: "2023. 02. 14",
    startTime: "11:00",
    endTime: "12:30",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 2,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 102,
      title: "내 강아지 인생 사진 찍어주기",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1002,
    status: "canceled",
    reviewSubmitted: false,
    totalPrice: 35000,
    headCount: 1,
    date: "2023. 02. 11",
    startTime: "13:00",
    endTime: "14:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 3,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 103,
      title: "이색 앵무새 카페에서 앵무새와 친구 되기",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1003,
    status: "declined",
    reviewSubmitted: false,
    totalPrice: 60000,
    headCount: 3,
    date: "2023. 01. 31",
    startTime: "10:00",
    endTime: "12:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 4,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 104,
      title: "발리 코끼리 목욕 체험",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1004,
    status: "completed",
    reviewSubmitted: false,
    totalPrice: 40000,
    headCount: 2,
    date: "2023. 01. 14",
    startTime: "16:00",
    endTime: "17:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 5,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 105,
      title: "발리 코끼리 목욕 체험",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1005,
    status: "completed",
    reviewSubmitted: true,
    totalPrice: 35000,
    headCount: 2,
    date: "2023. 01. 14",
    startTime: "15:00",
    endTime: "16:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 6,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 106,
      title: "열기구 페스티벌",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1006,
    status: "confirmed",
    reviewSubmitted: false,
    totalPrice: 70000,
    headCount: 2,
    date: "2023. 01. 10",
    startTime: "10:00",
    endTime: "12:30",
    createdAt: "",
    updatedAt: "",
  },
  {
    id: 7,
    teamId: "team-1",
    userId: 7,
    activity: {
      id: 101,
      title: "함께 배우면 즐거운 스트릿 댄스",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1001,
    status: "pending",
    reviewSubmitted: false,
    totalPrice: 10000,
    headCount: 1,
    date: "2023. 02. 14",
    startTime: "11:00",
    endTime: "12:30",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 8,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 102,
      title: "내 강아지 인생 사진 찍어주기",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1002,
    status: "canceled",
    reviewSubmitted: false,
    totalPrice: 35000,
    headCount: 1,
    date: "2023. 02. 11",
    startTime: "13:00",
    endTime: "14:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 9,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 103,
      title: "이색 앵무새 카페에서 앵무새와 친구 되기",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1003,
    status: "declined",
    reviewSubmitted: false,
    totalPrice: 60000,
    headCount: 3,
    date: "2023. 01. 31",
    startTime: "10:00",
    endTime: "12:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 10,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 104,
      title: "발리 코끼리 목욕 체험",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1004,
    status: "completed",
    reviewSubmitted: false,
    totalPrice: 40000,
    headCount: 2,
    date: "2023. 01. 14",
    startTime: "16:00",
    endTime: "17:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 11,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 105,
      title: "발리 코끼리 목욕 체험",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1005,
    status: "completed",
    reviewSubmitted: true,
    totalPrice: 35000,
    headCount: 2,
    date: "2023. 01. 14",
    startTime: "15:00",
    endTime: "16:00",
    createdAt: "",
    updatedAt: "",
  },

  {
    id: 12,
    teamId: "team-1",
    userId: 1,
    activity: {
      id: 106,
      title: "열기구 페스티벌",
      bannerImageUrl: "/images/test/test-card-image.png",
    },
    scheduleId: 1006,
    status: "confirmed",
    reviewSubmitted: false,
    totalPrice: 70000,
    headCount: 2,
    date: "2023. 01. 10",
    startTime: "10:00",
    endTime: "12:30",
    createdAt: "",
    updatedAt: "",
  },
];
